# Generated by Django 3.2.7 on 2021-09-20 14:28

from django.db import migrations, models
import django.db.models.deletion
import model_events.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TFKModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=(model_events.mixins.EventActionModelMixin, model_events.mixins.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TFKModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=(model_events.mixins.EventActionModelMixin, model_events.mixins.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TM2MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=(model_events.mixins.EventActionModelMixin, model_events.mixins.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=1024)),
                ('int_field', models.IntegerField(default=0)),
                ('boolean_field', models.BooleanField(default=False)),
                ('pre_create_field', models.BooleanField(default=False)),
                ('post_create_field', models.BooleanField(default=False)),
                ('pre_save_field', models.BooleanField(default=False)),
                ('post_save_field', models.BooleanField(default=False)),
                ('pre_delete_field', models.BooleanField(default=False)),
                ('post_delete_field', models.BooleanField(default=False)),
                ('fk_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.tfkmodel')),
                ('fk_field_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.tfkmodel2')),
                ('m2m_field', models.ManyToManyField(null=True, to='tests.TM2MModel')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_events.mixins.EventActionModelMixin, model_events.mixins.ModelDiffMixin, models.Model),
        ),
    ]
